alarm[0] = 10;
depth = orders.player - 1;
image_speed = 0;
sprite_index = Player.sprite_index;
image_index = Player.image_index;
image_angle = Player.image_angle;
image_xscale = Player.image_xscale;
image_alpha = 0.5;
image_blend = make_colour_rgb(100, 220, 255);